#server.port=8082

## DB
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.schema=public
spring.datasource.hikari.connection-init-sql=CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
spring.jpa.show-sql=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog.xml

server.servlet.context-path=/api

# Swagger
springdoc.api-docs.path=/api-docs
#http://localhost:8080/api/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html